server:
  servlet:
    context-path: /


logging:
  level:
    root: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: sample
    password: sample
    url: jdbc:mysql://localhost:13306/sample?allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.name}
      password: ${spring.datasource.password}
      schema: sample
  docker:
    compose:
      enabled: true #prd???false?????????????????
      lifecycle-management: start_only
  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    user: ${spring.datasource.name}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas: ${spring.datasource.hikari.schema}
    table: sample_version
